const courseDetails = [
  {
    id: 1,
    name: "Guitar Basics",
    description: "Introduction to guitar playing",
    instructor: "John Doe",
    instrument: "Guitar",
    dayOfWeek: "Monday",
    noOfStudents: 10,
    price: 100,
    status: "Active",
  },
  {
    id: 2,
    name: "Piano for Beginners",
    description: "Learn the basics of piano",
    instructor: "Jane Smith",
    instrument: "Piano",
    dayOfWeek: "Tuesday",
    noOfStudents: 8,
    price: 120,
    status: "Active",
  },
  {
    id: 3,
    name: "Advanced Drumming",
    description: "Advanced techniques for drummers",
    instructor: "Mike Johnson",
    instrument: "Drums",
    dayOfWeek: "Wednesday",
    noOfStudents: 6,
    price: 150,
    status: "Active",
  },
  {
    id: 4,
    name: "Violin Masterclass",
    description: "Master violin playing",
    instructor: "Emily Davis",
    instrument: "Violin",
    dayOfWeek: "Thursday",
    noOfStudents: 5,
    price: 200,
    status: "Active",
  },
  {
    id: 5,
    name: "Singing Lessons",
    description: "Improve your singing voice",
    instructor: "Chris Brown",
    instrument: "Voice",
    dayOfWeek: "Friday",
    noOfStudents: 12,
    price: 80,
    status: "Active",
  },
  {
    id: 6,
    name: "Flute Fundamentals",
    description: "Basics of flute playing",
    instructor: "Sarah Wilson",
    instrument: "Flute",
    dayOfWeek: "Monday",
    noOfStudents: 7,
    price: 90,
    status: "Active",
  },
  {
    id: 7,
    name: "Cello Intermediate",
    description: "Intermediate cello techniques",
    instructor: "David Lee",
    instrument: "Cello",
    dayOfWeek: "Tuesday",
    noOfStudents: 4,
    price: 130,
    status: "Active",
  },
  {
    id: 8,
    name: "Clarinet Basics",
    description: "Introduction to clarinet",
    instructor: "Megan Taylor",
    instrument: "Clarinet",
    dayOfWeek: "Wednesday",
    noOfStudents: 9,
    price: 110,
    status: "Active",
  },
  {
    id: 9,
    name: "Trumpet Techniques",
    description: "Learn trumpet playing",
    instructor: "James Anderson",
    instrument: "Trumpet",
    dayOfWeek: "Thursday",
    noOfStudents: 11,
    price: 95,
    status: "Active",
  },
  {
    id: 10,
    name: "Saxophone Basics",
    description: "Introduction to saxophone",
    instructor: "Laura Martinez",
    instrument: "Saxophone",
    dayOfWeek: "Friday",
    noOfStudents: 8,
    price: 100,
    status: "Active",
  },
  {
    id: 11,
    name: "Bass Guitar 101",
    description: "Basics of bass guitar",
    instructor: "Robert Garcia",
    instrument: "Bass Guitar",
    dayOfWeek: "Monday",
    noOfStudents: 6,
    price: 85,
    status: "Active",
  },
  {
    id: 12,
    name: "Harp Harmony",
    description: "Learn to play the harp",
    instructor: "Lisa Rodriguez",
    instrument: "Harp",
    dayOfWeek: "Tuesday",
    noOfStudents: 3,
    price: 160,
    status: "Active",
  },
  {
    id: 13,
    name: "Advanced Guitar",
    description: "Advanced guitar techniques",
    instructor: "Mark Wilson",
    instrument: "Guitar",
    dayOfWeek: "Wednesday",
    noOfStudents: 5,
    price: 140,
    status: "Active",
  },
  {
    id: 14,
    name: "Jazz Piano",
    description: "Learn jazz piano",
    instructor: "Nancy King",
    instrument: "Piano",
    dayOfWeek: "Thursday",
    noOfStudents: 10,
    price: 130,
    status: "Active",
  },
  {
    id: 15,
    name: "Drum Set Techniques",
    description: "Learn drum set playing",
    instructor: "Paul Scott",
    instrument: "Drums",
    dayOfWeek: "Friday",
    noOfStudents: 7,
    price: 100,
    status: "Active",
  },
  {
    id: 16,
    name: "Orchestral Violin",
    description: "Violin for orchestral settings",
    instructor: "Sophia Green",
    instrument: "Violin",
    dayOfWeek: "Monday",
    noOfStudents: 8,
    price: 150,
    status: "Active",
  },
  {
    id: 17,
    name: "Choral Singing",
    description: "Group singing techniques",
    instructor: "Kevin Baker",
    instrument: "Voice",
    dayOfWeek: "Tuesday",
    noOfStudents: 15,
    price: 75,
    status: "Active",
  },
  {
    id: 18,
    name: "Flute Ensemble",
    description: "Flute ensemble playing",
    instructor: "Amy Campbell",
    instrument: "Flute",
    dayOfWeek: "Wednesday",
    noOfStudents: 6,
    price: 120,
    status: "Active",
  },
  {
    id: 19,
    name: "Cello for Beginners",
    description: "Introduction to cello",
    instructor: "Richard Nelson",
    instrument: "Cello",
    dayOfWeek: "Thursday",
    noOfStudents: 4,
    price: 110,
    status: "Active",
  },
  {
    id: 20,
    name: "Clarinet Choir",
    description: "Clarinet choir techniques",
    instructor: "Jessica Carter",
    instrument: "Clarinet",
    dayOfWeek: "Friday",
    noOfStudents: 9,
    price: 105,
    status: "Active",
  },
  {
    id: 21,
    name: "Trumpet Mastery",
    description: "Advanced trumpet techniques",
    instructor: "Daniel Mitchell",
    instrument: "Trumpet",
    dayOfWeek: "Monday",
    noOfStudents: 5,
    price: 145,
    status: "Active",
  },
  {
    id: 22,
    name: "Saxophone Jazz",
    description: "Jazz saxophone playing",
    instructor: "Mary Perez",
    instrument: "Saxophone",
    dayOfWeek: "Tuesday",
    noOfStudents: 10,
    price: 135,
    status: "Active",
  },
  {
    id: 23,
    name: "Bass Guitar Techniques",
    description: "Learn advanced bass guitar",
    instructor: "Christopher White",
    instrument: "Bass Guitar",
    dayOfWeek: "Wednesday",
    noOfStudents: 6,
    price: 90,
    status: "Active",
  },
  {
    id: 24,
    name: "Harp for Beginners",
    description: "Introduction to harp",
    instructor: "Angela Harris",
    instrument: "Harp",
    dayOfWeek: "Thursday",
    noOfStudents: 3,
    price: 150,
    status: "Active",
  },
  {
    id: 25,
    name: "Guitar Improvisation",
    description: "Learn guitar improvisation",
    instructor: "Brian Lewis",
    instrument: "Guitar",
    dayOfWeek: "Friday",
    noOfStudents: 7,
    price: 125,
    status: "Active",
  },
  {
    id: 26,
    name: "Classical Piano",
    description: "Learn classical piano",
    instructor: "Kathryn Young",
    instrument: "Piano",
    dayOfWeek: "Monday",
    noOfStudents: 8,
    price: 130,
    status: "Active",
  },
  {
    id: 27,
    name: "Rock Drumming",
    description: "Learn rock drumming",
    instructor: "George Walker",
    instrument: "Drums",
    dayOfWeek: "Tuesday",
    noOfStudents: 6,
    price: 100,
    status: "Active",
  },
  {
    id: 28,
    name: "Violin Virtuosity",
    description: "Advanced violin techniques",
    instructor: "Sandra Hall",
    instrument: "Violin",
    dayOfWeek: "Wednesday",
    noOfStudents: 5,
    price: 160,
    status: "Active",
  },
  {
    id: 29,
    name: "Voice Training",
    description: "Improve your singing voice",
    instructor: "Betty Allen",
    instrument: "Voice",
    dayOfWeek: "Thursday",
    noOfStudents: 12,
    price: 80,
    status: "Active",
  },
  {
    id: 30,
    name: "Flute Mastery",
    description: "Master flute playing",
    instructor: "Frank Young",
    instrument: "Flute",
    dayOfWeek: "Friday",
    noOfStudents: 7,
    price: 95,
    status: "Active",
  },
  {
    id: 31,
    name: "Cello Ensemble",
    description: "Learn cello ensemble playing",
    instructor: "Martha King",
    instrument: "Cello",
    dayOfWeek: "Monday",
    noOfStudents: 4,
    price: 130,
    status: "Active",
  },
];

export default courseDetails;
